---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: cloudnative-pg
        group: Database
        url: tcp://postgres-lb.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions: ["[CONNECTED] == true"]
        alerts:
          - type: pushover
