apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        VIKUNJA_DATABASE_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: &dbName vikunja
        VIKUNJA_DATABASE_USER: &dbUser vikunja
        VIKUNJA_DATABASE_PASSWORD: "{{ .INIT_POSTGRES_PASS }}"
        VIKUNJA_SERVICE_JWTSECRET: "{{ .VIKUNJA_SERVICE_JWTSECRET }}"
        VIKUNJA_MAILER_USERNAME: "{{ .SMTP_USERNAME }}"
        VIKUNJA_MAILER_PASSWORD: "{{ .SMTP_PASSWORD }}"
        # DB_HOST: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/wikijs
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: "{{ .INIT_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
  #APP
  - secretKey: VIKUNJA_SERVICE_JWTSECRET
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: VIKUNJA_SERVICE_JWTSECRET
      ### Postgres Init
  - secretKey: INIT_POSTGRES_PASS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: INIT_POSTGRES_PASS
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password
      #### SMTP
  - secretKey: SMTP_USERNAME
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_USERNAME
  - secretKey: SMTP_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_PASSWORD
