apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mealie-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        DEFAULT_EMAIL: "{{ .DEFAULT_EMAIL_MEALIE }}"
        DEFAULT_PASSWORD: "{{ .DEFAULT_PASSWORD_MEALIE }}"
        DEFAULT_GROUP: Home
        # DOESNT WORK DONT KNOW WHY???
        POSTGRES_DB: &dbName mealie
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: &dbUser mealie
        POSTGRES_PASS: "{{ .INIT_POSTGRES_PASS }}"
        POSTGRES_SERVER: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres16-rw.database.svc.cluster.local:5432/mealie
        # SMTP
        # SMTP_FROM_EMAIL: "mealie@mg.noms.cc"
        # SMTP_FROM_EMAIL: "mealie@{{ .SMTP_SERVER }}"
        SMTP_USER: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_SERVER: "{{ .SMTP_SERVER }}"
        # SMTP_PORT: "{{ .SMTP_PORT }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: "{{ .INIT_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
  - secretKey: DEFAULT_EMAIL_MEALIE
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: DEFAULT_EMAIL_MEALIE
  - secretKey: DEFAULT_PASSWORD_MEALIE
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: DEFAULT_PASSWORD_MEALIE
      #### SMTP
  - secretKey: SMTP_DOMAIN
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_DOMAIN
  - secretKey: SMTP_USERNAME
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_USERNAME
  - secretKey: SMTP_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_PASSWORD
  - secretKey: SMTP_SERVER
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_SERVER
  # - secretKey: SMTP_PORT
  #   sourceRef:
  #     storeRef:
  #       name: bitwarden-fields
  #       kind: ClusterSecretStore
  #   remoteRef:
  #     key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
  #     property: SMTP_PORT
  ### Postgres Init
  - secretKey: INIT_POSTGRES_PASS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: INIT_POSTGRES_PASS
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password
