---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        # annotations:
        #   secret.reloader.stakater.com/reload: &secret mealie-secret
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
              pullPolicy: IfNotPresent
            envFrom:
            - secretRef:
                name: mealie-secret #*secret

        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.0.0-RC1.1
            env:
              ALLOW_SIGNUP: true
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
              BASE_URL: https://meals.${SECRET_DOMAIN}
              # SMTP_HOST: smtp.mailgun.org
              SMTP_HOST: smtp-relay.networking.svc.cluster.local
              SMTP_PORT: 2525
              SMTP_FROM_NAME: Mealie
              SMTP_FROM_EMAIL: mealie@${SECRET_DOMAIN}
              # SMTP_FROM_EMAIL: mealie@${SMTP_DOMAIN}
              SMTP_AUTH_STRATEGY: None # 'TLS', 'SSL', 'None'
              DB_ENGINE: postgresql
              POSTGRES_PORT: 5432
              # Login does not work
              # DEFAULT_EMAIL: admin@${SECRET_DOMAIN}
              DEFAULT_EMAIL:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: DEFAULT_EMAIL
              DEFAULT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: DEFAULT_PASSWORD
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: POSTGRES_DB
              POSTGRES_HOST:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: POSTGRES_HOST
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: POSTGRES_USER
              POSTGRES_PASS:
                valueFrom:
                  secretKeyRef:
                    name: mealie-secret
                    key: POSTGRES_PASS
            resources:
              requests:
                cpu: 5m
                memory: 256Mi
              limits:
                memory: 512Mi

    service:
      main:
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Recipes
          hajimari.io/group: Services
          hajimari.io/icon: mdi:chef-hat
          hajimari.io/info: Meal Recipes
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Self-hosted Recipes!
          gethomepage.dev/group: Services
          gethomepage.dev/icon: mealie
          gethomepage.dev/name: Mealie
        hosts:
        - host: &host "meals.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *host

    persistence:
      data:
        existingClaim: mealie-data
        globalMounts:
        - path: /app/data
