apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radicale-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        users: "{{ .RADICALE_USERS }}"
        # users: |-
        #   user1:{{ index . "radicale_user1" }}
        #   user2:{{ index . "radicale_user2" }}
        #   user3:{{ index . "radicale_user3" }}
        #   user4:{{ index . "radicale_user4" }}
  refreshInterval: 15m
  data:
  #APP
  - secretKey: RADICALE_USERS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: RADICALE_USERS
