---
apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: radicale
        group: external
        url: https://cal.${SECRET_DOMAIN}
        interval: 30m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
