---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-radicale
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-hostpath #nfs

