---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hajimari
spec:
  interval: 30m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    hajimari:
      title: Apps
      lightTheme: espresso
      darkTheme: horizon
      alwaysTargetBlank: true
      showGreeting: false
      showAppGroups: true
      showAppStatus: false
      showBookmarkGroups: true
      showGlobalBookmarks: true
      showAppUrls: false
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - collaboration
          - default
          - database
          - flux-system
          - home
          - kube-system
          - networking
          - media
          - monitoring
          - security
          - services
          - storage
      searchProviders:
        - name: Google
          token: g
          icon: simple-icons:google
          searchUrl: https://www.google.com/search?q={query}
          url: https://www.google.com
        - name: DuckDuckGo
          token: d
          icon: simple-icons:duckduckgo
          searchUrl: https://duckduckgo.com/?q={query}
          url: https://duckduckgo.com
        - name: IMDB
          token: i
          icon: simple-icons:imdb
          searchUrl: https://www.imdb.com/find?q={query}
          url: https://www.imdb.com
        - name: Reddit
          token: r
          icon: simple-icons:reddit
          searchUrl: https://www.reddit.com/search?q={query}
          url: https://www.reddit.com
        - name: YouTube
          token: 'y'
          icon: simple-icons:youtube
          searchUrl: https://www.youtube.com/results?search_query={query}
          url: https://www.youtube.com
        - name: Spotify
          token: s
          icon: simple-icons:spotify
          searchUrl: hhttps://open.spotify.com/search/{query}
          url: https://open.spotify.com
      customApps:
        - name: Some External Cluster Service
          url: http://192.168.1.100:5000
          icon: test-tube
      globalBookmarks:
        - group: Communicate
          bookmarks:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - group: Cloud
          bookmarks:
            - name: Box
              url: "https://box.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - group: Media
          bookmarks:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: Trakt
              url: "http://trakt.tv"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - group: Git
          bookmarks:
            - name: k8s-at-home
              url: 'https://kubesearch.dev/'
            - name: k3s-home-cluster
              url: 'https://github.com/NontQ/home-ops'
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "apps.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podAnnotations:
      configmap.reloader.stakater.com/reload: hajimari-settings
    persistence:
      data:
        enabled: true
        type: emptyDir
    resources:
      requests:
        cpu: 100m
        memory: 128M
