apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-relay-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # Postgres Init
        SMTP_DOMAIN: "{{ .SMTP_DOMAIN }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_SERVER: "{{ .SMTP_SERVER }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
  refreshInterval: 15m
  data:
  - secretKey: SMTP_DOMAIN
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_DOMAIN
  - secretKey: SMTP_USERNAME
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_USERNAME
  - secretKey: SMTP_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_PASSWORD
  - secretKey: SMTP_SERVER
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_SERVER
  - secretKey: SMTP_PORT
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 2783d028-0ed7-42ec-a36f-b0b6010e6440
      property: SMTP_PORT
