---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-relay-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: smtp-relay
        group: guarded
        interval: 1h
        url: 1.1.1.1
        dns:
          query-name: mg.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
