---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app smtp-relay
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/foxcpp/maddy
              tag: 0.7.0
            env:
              DEBUG: "true"
              # SMTP_DOMAIN: "${SECRET_DOMAIN}"
              # SMTP_SERVER: "smtp.mailgun.org"
              # SMTP_PORT: "587"
            envFrom:
              - secretRef:
                  name: smtp-relay-secret
            resources:
              requests:
                cpu: 10m
                memory: 10Mi
              limits:
                memory: 50Mi
    service:
      main:
        # type: LoadBalancer
        # loadBalancerIP: "10.69.69.25"
        # externalTrafficPolicy: Local
        ports:
          http:
            port: 2525
          metrics:
            enabled: true
            port: 9749
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      config:
        enabled: true
        type: configMap
        name: smtp-relay-configmap
        globalMounts:
          - path: /data/maddy.conf
            subPath: maddy.conf
            readOnly: true
      data:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
