apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:jAw5jmUrh58gUd7C7+chhuHwAP3vQoyD,iv:gFpcaeMcYTTOLN8wBdBRU7VCDKyx7mtBiUxgk5zauCw=,tag:T7gxkj0YS232kXRyeyNEnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axv7y2kctg80u3530nzx5ypskuz92qn588xyufzwjwakr3me04cshqrvv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWWhLMjY5TC9jNUFwd2NB
            ZFd6WTZWUDVXZHA1aWxpbHp0aVpzTTc5UkhBCk80ZGNxUkZoMzhqWlA1TGIxcUts
            Ym8vNStPcVFhN2IvR2M0bGVuS2RyVUkKLS0tIEJWN1JzZlk2RzY4YnJxTDRtTkJB
            RHIvQlJPcmFkZVVSZE9IU3FZTE9Qd2MKIpO6W6YPvAFYmM2j5cjhnJT++WgGDNTa
            53WIL/O4q5LwPbptclWlOER0OqkZ/9nzmGM++y6/9nNJiexTC6RUAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T04:29:31Z"
    mac: ENC[AES256_GCM,data:U12erFLz9XPNfI/J0bvn9cRs2CcLQETbN70dTGYSzu3NmWxwNMYM5x5FFzAy45UhSKVdQ9/gy/LOLghprn8dHjofNnMAgbBfme01hrhzrd9bUqXomNMjyE6VOH4ZChZJQ8a5QvEcj/UUGoVTy0Ur1ZYhR0plXiBKxnOjkWRd6Fw=,iv:kdyLU+g5f2VSKRE5FSH6jqhssz8xzj9MiT8ytds9RUI=,tag:TIOVLimsdJmg02UqFZIntw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
