apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PAPERLESS_DBENGINE: postgresql
        PAPERLESS_DBPORT: "5432"
        PAPERLESS_DBNAME: &dbName paperless
        PAPERLESS_DBHOST: &dbHost postgres16-rw.database.svc.cluster.local
        PAPERLESS_DBUSER: &dbUser paperless
        PAPERLESS_DBPASS: &dbPass "{{ .INIT_POSTGRES_PASS }}"
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
  - secretKey: PAPERLESS_ADMIN_USER
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: PAPERLESS_ADMIN_USER
  - secretKey: PAPERLESS_ADMIN_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: PAPERLESS_ADMIN_PASSWORD
  - secretKey: PAPERLESS_SECRET_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: b04a2bf9-a870-4560-a36b-b0b601184693
      property: PAPERLESS_SECRET_KEY
  ### Postgres Init
  - secretKey: INIT_POSTGRES_PASS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: INIT_POSTGRES_PASS
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password
