---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: paperless
        group: guarded
        url: 1.1.1.1
        interval: 1m
        dns:
          query-name: docs.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
