---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
          secret.reloader.stakater.com/reload: &secret paperless-secret
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 15.5
            envFrom:
            - secretRef:
                name: paperless-secret
        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 1.17.4
            env:
              # Configure application
              PAPERLESS_URL: https://docs.${SECRET_DOMAIN}
              PAPERLESS_PORT: &port 80
              PAPERLESS_TIME_ZONE: ${TIMEZONE}
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              # Configure Remote User auth
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"
              PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_REMOTE_USER
              PAPERLESS_LOGOUT_REDIRECT_URL: https://auth.${SECRET_DOMAIN}/logout
              # # Configure folders
              # PAPERLESS_CONSUMPTION_DIR: /library/consume
              # PAPERLESS_DATA_DIR: /library/data
              # PAPERLESS_EXPORT_DIR: /library/export
              # PAPERLESS_MEDIA_ROOT: /library/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              # Configure redis,tike,gotenberg integration
              PAPERLESS_REDIS: redis://localhost:6379
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              # Configure user permissions
              USERMAP_UID: 1022
              USERMAP_GID: 1022
            envFrom:
            - secretRef:
                name: *secret
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 5000Mi
          gotenburg:
            image:
              repository: thecodingmachine/gotenberg
              tag: 7.9.2
            env:
            - {name: DISABLE_GOOGLE_CHROME, value: "1"}
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.2.3
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.0-full
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: Paperless
          hajimari.io/group: Services
          hajimari.io/icon: mdi:file-multiple
          hajimari.io/info: Document Management
        hosts:
        - host: &host "docs.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              name: main
              port: http
        tls:
        - hosts:
          - *host

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: paperless-config-v1
        advancedMounts:
          main:
            main:
              - path: /library/paperless/data
                subPath: paperless/data
              - path: /library/paperless/media
                subPath: paperless/media
              - path: /library/paperless/export
                subPath: paperless/export
              - path: /library/paperless/consume
                subPath: paperless/consume
