---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-config-v1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath #nfs
