apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:WhTNgiTl8rSqV/gg52rGzDCd0sQUNIkdukctRc0+CmpFHYbSGUg0l2y68xKe8zQMG/lbykMGLRvkEXuP,iv:PjsDOG6wtfNGxF0d27VDN9zUnXSCzJ1GDTqE9n7LGaU=,tag:EpHPqvWDzX90mj5LEnRayg==,type:str]
    username: ENC[AES256_GCM,data:wL/GCE4=,iv:zZwRnqsxoicH9yJLk77sw+BnpawvLA0S1wt1vUzi/ng=,tag:zVaaEmTfEX/oCrKrR5nL3A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axv7y2kctg80u3530nzx5ypskuz92qn588xyufzwjwakr3me04cshqrvv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVm5sVzY0UXd0dnpFRzRa
            Q052aHRQVG5kdWZZUkd0aHhUZnYvTjVXQ1hrCnByUFNkK20ybG5DNEV1dEl6U3VC
            QXRjS3k0SkM5MHoxY29SNmRlcHQ0Q1UKLS0tIHhaL3RMRUpqMmROWjFmVTVDdmxv
            SWlodjNJSFZxczdRTVczUmcxMkRjZ28KxoUh9yIy5dfsK0E1i/MhrCEiU8RyrocZ
            kmB6z/+/3N/sbEuv6eoAdEM08zUDSdWfG5IJ0JR+jRkBltJD/08Sxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T03:59:45Z"
    mac: ENC[AES256_GCM,data:SDJ0AsZaHX8gVb1EBGprFGtj45UM8OCDS5LUl4Xmj92HV1UvxDMs1M5SIkeeRxPuQFL/eV9DqZ9PGZlxDAek4QJE0jOJkCpnWFKP70/u9A0hTU4H4NmkPsClNGZ98teZtMkC6c71CvNhkk8w7bqUS0iAdwVynM8YT3IqLnZlI+I=,iv:kh5m/GAl5zq6QubJLMOkV2AccQ9CyYyHJ5zn0+z7pWE=,tag:7g36zoO0ajmVyBQ0wSWLAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
