apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pplgOF0LI4EH+Bbh0TJNI1X9LoU=,iv:YCxjKZOKi8YOmiiL3I5MG1/NankIN2tZNbnOAzGF/6k=,tag:LI2gdmXY22irv/6BclCaKQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nPPWja54Az1M+rY61hKoTSqHQSSmfZ92OstSlpJHTKMi5bUA,iv:JY1SprpFoGCDakN/LaxrQ8lG7MxpKQa/TiR9x+k3vdU=,tag:NWlmbJ2GY9S0x3B/s9UdFg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:c+t9tlDzlA==,iv:5/PJTlYqzCcUzHT+rz43j3xT/9ODuPYagVVAKFw6SL8=,tag:dvwr4uW1oijZokYyehsTRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axv7y2kctg80u3530nzx5ypskuz92qn588xyufzwjwakr3me04cshqrvv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYjFocXRvTC9iYzRRaXVH
            N3pHbHAzWWtmN1BDckZHQmhwOGxZMllRTGpvCkw1RmErajBkbjNIOXM3ZGtCZGhM
            TmVBaTd1dmM3aUtKQXEwUENzWGx4OEkKLS0tIFh4cTFha0p1SVh4SHpuL0NQYTVu
            TjdOVCtDa0lsYlZnV3JBeldQeVR1OE0KGP2oEdTTAWvj85eI7PL2umRrqiJM1crC
            54oGvTOkySY86qcGUTknQBCdeGW0IfZSdMG8XQsg+cXUUBdZDGYKgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T04:29:32Z"
    mac: ENC[AES256_GCM,data:qssrIzVb6nkiLnuXG1QP/oYJYmEWvTGyhxYoN5sMDiPz7jJEVK+ugceOMWdRJHtFi7++JVns+th90U3zx2IcxTRbm/W+9vBwy/kHXS6f8FmstF8MScn/4LGrJ6YEncwAifB/7LZv1tFfWdHnW6is67jr4wXNvnTeSvkt2X7qTzc=,iv:bFCxcuTTVb5Z+tbEDPG6LATBqsdLW0oOp1vQpxdBzGQ=,tag:BB8faeYKCTXg0SYpWOZofg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
