apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:aoQNgFfJ5FNRJRbd,iv:oaHLEe6YIBWxV+JniO7grNIqU3mKWKspXe2UJ+qoJWk=,tag:IlvqO+rhvH476wIumdTcLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1axv7y2kctg80u3530nzx5ypskuz92qn588xyufzwjwakr3me04cshqrvv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeWJWVlhuQXRLK1lnSm56
            TUEzZjBpQ2VqWDd4NllCODRISVB2KzlRcDI0ClRFbThCVGZPVzVPQTZjNktHVURw
            eTE5ZUZTNlIzOEU3TDhuRmpqV1Q0UVkKLS0tIDlTQ1N4TU5yLzA4UDlGZXRHb2t2
            OWV4QkdpbHJzcTJTaXMzQmJUR1h0dm8Kisren2vt+bIyXhAsfCJ31JSctU1Pd03h
            bb9tkgybh7xbMGP1J3L7Z58d+tU4PBUCkWy9J6/TPET2K/lKNAEtZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-03T04:29:32Z"
    mac: ENC[AES256_GCM,data:UPsJYL7ynRnMGo0FrmPDctKmFbcjCWx+P6qcXtXWfAOV0JcoHYEhtJMZKDdhPa6lbX8+I7FqQJZkXbWHdrEvaJRy+/MLPUPHVNz5Kc6khAAxoDmbPyX2ldUK88mBwfv5YA2XTsDAzsBz1YmutU3iD+LmKAp9Z1nadaCxZKoOhCk=,iv:8jZ5L6eTId7SNr+x+L8kSSs1VL5AfOxgbN3nmi5i1iE=,tag:bCmrZM341g7pZ1hgMpJREg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
