---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless-app
  namespace: flux-system
spec:
  targetNamespace: services
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-bitwarden
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/services/paperless/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
