apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-external-secret
spec:
  target:
    name: pgadmin
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: Opaque
      data:
        password: |-
          {{ .PGADMIN_PASSWORD }}
        PGADMIN_DEFAULT_PASSWORD: |-
          {{ .PGADMIN_DEFAULT_PASSWORD }}
  data:
  - secretKey: PGADMIN_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: PGADMIN_PASSWORD
  - secretKey: PGADMIN_DEFAULT_PASSWORD
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: PGADMIN_DEFAULT_PASSWORD
