---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin4
      version: 1.24.0
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: democratic-csi-local
      namespace: kube-system
  values:
    env:
      email: admin@${SECRET_DOMAIN}
    existingSecret: *app
    # secretKeys:
    #   pgadminPasswordKey: password
    serverDefinitions:
      enabled: true
      servers:
          default:
              Name: default
              Group: Servers
              Port: 5432
              Username: postgres
              Host: postgres16-rw.database.svc.cluster.local
              SSLMode: prefer
              MaintenanceDB: postgres
    strategy:
      type: Recreate

    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/appName: "Postgres Admin"
        hajimari.io/icon: "simple-icons:postgresql"
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      hosts:
        - host: &host "pgadmin.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    persistentVolume:
      enabled: true
      existingClaim: *app

    resources:
      # required to initialize
      requests:
        cpu: 25m
        memory: 204Mi
      limits:
        memory: 1024Mi

    annotations:
      reloader.stakater.com/search: "true"
      # secret.reloader.stakater.com/reload: "pgadmin"
