apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
  - secretKey: POSTGRES_SUPER_USER
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: username
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password
  - secretKey: AWS_ACCESS_KEY_ID
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: AWS_SECRET_ACCESS_KEY
