---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PUSHOVER_API_TOKEN_GATUS: "{{ .PUSHOVER_API_TOKEN_GATUS }}"
        PUSHOVER_API_USERKEY: "{{ .PUSHOVER_API_USERKEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: gatus
        INIT_POSTGRES_PASS: "{{ .INIT_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
  - secretKey: PUSHOVER_API_TOKEN_GATUS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: e1249dbe-4c7a-450f-a259-b0b6010d4d6d
      property: PUSHOVER_API_TOKEN_GATUS
  - secretKey: PUSHOVER_API_USERKEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: e1249dbe-4c7a-450f-a259-b0b6010d4d6d
      property: PUSHOVER_API_USERKEY
#### Postgres Init
  - secretKey: INIT_POSTGRES_PASS
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: INIT_POSTGRES_PASS
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password

