---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ext-postgres-operator-secret
spec:
  target:
    name: ext-postgres-operator-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_DEFAULT_DATABASE: postgres
        POSTGRES_URI_ARGS: ""
        POSTGRES_CLOUD_PROVIDER: ""
  data:
  - secretKey: POSTGRES_SUPER_USER
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: username
  - secretKey: POSTGRES_SUPER_PASS
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: ClusterSecretStore
    remoteRef:
      key: 3cab8b9c-3bd7-49f8-a7d2-b0b60104f6b3
      property: password
